export const DEMO_TEACHER = {
  id: "tch-001",
  code: "AEC-TCH-009",
  name: "Ustadh Muhammad Qasim",
  title: "Senior Quran & Tajweed Faculty / Al-Azhar Certified",
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  email: "ustadh.qasim@aecnetwork.com",
  phone: "+92 343 5999397",
  specialties: ["Quran Recitation", "Tajweed & Tarteel", "Qira'at", "Spoken Arabic"],
  totalStudents: 18,
  classesToday: 4,
  pendingGrading: 3,
  averageAttendanceRate: 97.4,
};

export const DEMO_TEACHER_CLASSES = [
  {
    id: "tcls-1",
    studentName: "Abdullah Akbar",
    studentCode: "AEC-STU-2026-001",
    subject: "Quran Recitation & Applied Tajweed",
    time: "5:00 PM - 5:45 PM (PKT)",
    meetingPlatform: "Google Meet",
    joinUrl: "https://meet.google.com/aec-live-class",
    status: "live_now",
    lessonTopic: "Surah Al-Mulk (Ayat 1-10) Revision & Makharij Assessment",
  },
  {
    id: "tcls-2",
    studentName: "Zaid Bin Tariq",
    studentCode: "AEC-STU-2026-015",
    subject: "Noorani Qaida & Basic Tajweed",
    time: "6:00 PM - 6:45 PM (PKT)",
    meetingPlatform: "Zoom",
    joinUrl: "https://zoom.us/j/923435999397",
    status: "scheduled",
    lessonTopic: "Lesson 8: Tanween and Noon Saakin Rules",
  },
  {
    id: "tcls-3",
    studentName: "Hamza Farooq",
    studentCode: "AEC-STU-2026-028",
    subject: "Hifz Revision & Memorization",
    time: "7:00 PM - 7:45 PM (PKT)",
    meetingPlatform: "Google Meet",
    joinUrl: "https://meet.google.com/aec-live-class-2",
    status: "scheduled",
    lessonTopic: "Juz 30 (Surah An-Naba to Al-Mutaffifin)",
  },
  {
    id: "tcls-4",
    studentName: "Ibrahim Malik (UK)",
    studentCode: "AEC-STU-2026-033",
    subject: "Spoken Arabic & Quran Vocabulary",
    time: "8:30 PM - 9:15 PM (PKT)",
    meetingPlatform: "Zoom",
    joinUrl: "https://zoom.us/j/923435999397",
    status: "scheduled",
    lessonTopic: "Everyday Arabic Phrases & Quranic Roots",
  },
];

export const DEMO_TEACHER_STUDENTS = [
  {
    id: "stu-1",
    code: "AEC-STU-2026-001",
    name: "Abdullah Akbar",
    program: "Quran Recitation & Applied Tajweed",
    level: "Intermediate",
    attendance: "96%",
    grade: "A+ (96%)",
    lastSession: "Yesterday",
    status: "Active",
  },
  {
    id: "stu-2",
    code: "AEC-STU-2026-015",
    name: "Zaid Bin Tariq",
    program: "Noorani Qaida & Basic Tajweed",
    level: "Beginner",
    attendance: "100%",
    grade: "A (92%)",
    lastSession: "2 days ago",
    status: "Active",
  },
  {
    id: "stu-3",
    code: "AEC-STU-2026-028",
    name: "Hamza Farooq",
    program: "Quran Memorization (Hifz)",
    level: "Advanced",
    attendance: "94%",
    grade: "A+ (98%)",
    lastSession: "Sept 20",
    status: "Active",
  },
  {
    id: "stu-4",
    code: "AEC-STU-2026-033",
    name: "Ibrahim Malik (UK)",
    program: "Spoken Arabic & Vocabulary",
    level: "Intermediate",
    attendance: "95%",
    grade: "A- (88%)",
    lastSession: "Sept 19",
    status: "Active",
  },
];

export const DEMO_PENDING_GRADING = [
  {
    id: "grd-1",
    student: "Abdullah Akbar",
    course: "Quran & Applied Tajweed",
    title: "Surah Al-Mulk Audio Recitation",
    submittedDate: "Today at 10:30 AM",
    fileUrl: "#",
    type: "Audio MP3 (3.2 MB)",
  },
  {
    id: "grd-2",
    student: "Zaid Bin Tariq",
    course: "Noorani Qaida",
    title: "Lesson 7 Reading Test Recording",
    submittedDate: "Yesterday",
    fileUrl: "#",
    type: "Audio M4A (1.8 MB)",
  },
  {
    id: "grd-3",
    student: "Ibrahim Malik",
    course: "Spoken Arabic",
    title: "Dialogue Worksheet #3",
    submittedDate: "Sept 21",
    fileUrl: "#",
    type: "PDF Document (450 KB)",
  },
];
